
package org.dobrodey.generate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RouterSenderService", targetNamespace = "http://sender.server.dobrodey.ru/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RouterSenderService {


    /**
     * 
     * @return
     *     returns org.dobrodey.generate.ListOfReport
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://sender.server.dobrodey.ru/RouterSenderService/getReportsTodayRequest", output = "http://sender.server.dobrodey.ru/RouterSenderService/getReportsTodayResponse")
    public ListOfReport getReportsToday();

    /**
     * 
     * @param arg0
     * @return
     *     returns org.dobrodey.generate.ListOfString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://sender.server.dobrodey.ru/RouterSenderService/getUserNamesByRoleRequest", output = "http://sender.server.dobrodey.ru/RouterSenderService/getUserNamesByRoleResponse")
    public ListOfString getUserNamesByRole(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws IOException_Exception
     */
    @WebMethod
    @Action(input = "http://sender.server.dobrodey.ru/RouterSenderService/pdfRequest", output = "http://sender.server.dobrodey.ru/RouterSenderService/pdfResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://sender.server.dobrodey.ru/RouterSenderService/pdf/Fault/IOException")
    })
    public void pdf(
        @WebParam(name = "arg0", partName = "arg0")
        byte[] arg0,
        @WebParam(name = "arg1", partName = "arg1")
        ListOfString arg1)
        throws IOException_Exception
    ;

}
