
package org.dobrodey.generate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RouterSenderService", targetNamespace = "http://router_web_service.example.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RouterSenderService {


    /**
     * 
     * @return
     *     returns org.dobrodey.generate.ListOfString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://router_web_service.example.com/RouterSenderService/getThreeDaysNotTrackingUsersRequest", output = "http://router_web_service.example.com/RouterSenderService/getThreeDaysNotTrackingUsersResponse")
    public ListOfString getThreeDaysNotTrackingUsers();

    /**
     * 
     * @return
     *     returns org.dobrodey.generate.ListOfString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://router_web_service.example.com/RouterSenderService/getOneDaysNotTrackingUsersRequest", output = "http://router_web_service.example.com/RouterSenderService/getOneDaysNotTrackingUsersResponse")
    public ListOfString getOneDaysNotTrackingUsers();

    /**
     * 
     * @return
     *     returns org.dobrodey.generate.ListOfReportSender
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://router_web_service.example.com/RouterSenderService/getReportsTodayRequest", output = "http://router_web_service.example.com/RouterSenderService/getReportsTodayResponse")
    public ListOfReportSender getReportsToday();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://router_web_service.example.com/RouterSenderService/notifyUserRequest", output = "http://router_web_service.example.com/RouterSenderService/notifyUserResponse")
    public void notifyUser(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.dobrodey.generate.ListOfString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://router_web_service.example.com/RouterSenderService/getUserNamesByRoleRequest", output = "http://router_web_service.example.com/RouterSenderService/getUserNamesByRoleResponse")
    public ListOfString getUserNamesByRole(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns org.dobrodey.generate.ListOfString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://router_web_service.example.com/RouterSenderService/getAdminsRequest", output = "http://router_web_service.example.com/RouterSenderService/getAdminsResponse")
    public ListOfString getAdmins();

    /**
     * 
     * @return
     *     returns org.dobrodey.generate.ListOfString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://router_web_service.example.com/RouterSenderService/getLecturersRequest", output = "http://router_web_service.example.com/RouterSenderService/getLecturersResponse")
    public ListOfString getLecturers();

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws IOException_Exception
     */
    @WebMethod
    @Action(input = "http://router_web_service.example.com/RouterSenderService/pdfRequest", output = "http://router_web_service.example.com/RouterSenderService/pdfResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://router_web_service.example.com/RouterSenderService/pdf/Fault/IOException")
    })
    public void pdf(
        @WebParam(name = "arg0", partName = "arg0")
        byte[] arg0,
        @WebParam(name = "arg1", partName = "arg1")
        ListOfString arg1)
        throws IOException_Exception
    ;

}
