
package org.dobrodey.generate;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RouterSenderServiceImplService", targetNamespace = "http://router_web_service.example.com/", wsdlLocation = "http://localhost:8082/ws/router?wsdl")
public class RouterSenderServiceImplService
    extends Service
{

    private final static URL ROUTERSENDERSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ROUTERSENDERSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ROUTERSENDERSERVICEIMPLSERVICE_QNAME = new QName("http://router_web_service.example.com/", "RouterSenderServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/ws/router?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROUTERSENDERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ROUTERSENDERSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public RouterSenderServiceImplService() {
        super(__getWsdlLocation(), ROUTERSENDERSERVICEIMPLSERVICE_QNAME);
    }

    public RouterSenderServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROUTERSENDERSERVICEIMPLSERVICE_QNAME, features);
    }

    public RouterSenderServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ROUTERSENDERSERVICEIMPLSERVICE_QNAME);
    }

    public RouterSenderServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROUTERSENDERSERVICEIMPLSERVICE_QNAME, features);
    }

    public RouterSenderServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RouterSenderServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RouterSenderService
     */
    @WebEndpoint(name = "RouterSenderServiceImplPort")
    public RouterSenderService getRouterSenderServiceImplPort() {
        return super.getPort(new QName("http://router_web_service.example.com/", "RouterSenderServiceImplPort"), RouterSenderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RouterSenderService
     */
    @WebEndpoint(name = "RouterSenderServiceImplPort")
    public RouterSenderService getRouterSenderServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://router_web_service.example.com/", "RouterSenderServiceImplPort"), RouterSenderService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROUTERSENDERSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ROUTERSENDERSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ROUTERSENDERSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
